class Error1 < Exception {}
class Error2 < Exception {}

try {
    throw Error1("error message");
    print("Try");
} catch (Error1, Error2) as e {
    print(e); # expect: Error1: error message
              # expect: Stacktrace (most recent call last):
              # expect:   [line 5] in <script>
} else {
    print("Else");
}
print("Done"); # expect: Done
