class Error1 < Exception {}
class Error2 < Exception {}


try {
    try {
        throw Error1("error message");
    } catch Error1 as e1 {
        print(e1); # expect: Error1: error message
                   # expect: Stacktrace (most recent call last):
                   # expect:   [line 7] in <script>
        throw Error2("error message");
    } catch Error2 as e2 {
        print(e2); 
    }
} catch Error2 as e {
    print(e); # expect: Error2: error message
              # expect: Stacktrace (most recent call last):
              # expect:   [line 12] in <script>
}


try {
    try {
        throw Error2("error message");
    } catch Error1 as e1 {
        print(e1);
    } catch Error2 as e2 {
        print(e2);  # expect: Error2: error message
                    # expect: Stacktrace (most recent call last):
                    # expect:   [line 25] in <script>
        throw Error1("error message");
    }
} catch Error1 as e {
    print(e); # expect: Error1: error message
              # expect: Stacktrace (most recent call last):
              # expect:   [line 32] in <script>
}
