class Error1 < Exception {}
class Error2 < Exception {}
class Error3 < Exception {}

try {
    throw Error2("error message");
    print("Try");
} catch Error1 as e1 {
    print(e1);
} catch Error2 as e2 {
    print(e2); # expect: Error2: error message
               # expect: Traceback (most recent call last):
               # expect:   File "test/exceptions/catch_multiple_blocks.gen", line 6, in <script>
               # expect:         throw Error2("error message");
               # expect:               ~~~~~~^^^^^^^^^^^^^^^^^ 
} catch Error3 as e3 {
    print(e3);
} else {
    print("Else");
}
print("Done"); # expect: Done
